---
- name: Update Story Consensus Node
  hosts: all
  become: true

  vars:
    consensus_version: "0.11.0-aac4bfe"
    home_dir: "/root"

  tasks:
    - name: Download new story-consensus version
      get_url:
        url: "https://story-geth-binaries.s3.us-west-1.amazonaws.com/story-public/story-linux-amd64-{{ consensus_version }}.tar.gz"
        dest: "{{ home_dir }}/story-linux-amd64-{{ consensus_version }}.tar.gz"

    - name: Extract new story-consensus binary
      unarchive:
        src: "{{ home_dir }}/story-linux-amd64-{{ consensus_version }}.tar.gz"
        dest: "{{ home_dir }}"
        remote_src: yes

    - name: Stop story-consensus-node service
      systemd:
        name: story-consensus-node
        state: stopped

    - name: Replace old story-consensus binary with new one
      copy:
        src: "{{ home_dir }}/story-linux-amd64-{{ consensus_version }}/story"
        dest: "/usr/local/bin/story"
        mode: '0755'
        remote_src: yes

    - name: Start story-consensus-node service
      systemd:
        name: story-consensus-node
        state: started

    - name: Clean up downloaded files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ home_dir }}/story-linux-amd64-{{ consensus_version }}.tar.gz"
        - "{{ home_dir }}/story-linux-amd64-{{ consensus_version }}"

    - name: Restart story-geth-node service
      systemd:
        name: story-geth-node
        state: restarted

    - name: Restart story-consensus-node service
      systemd:
        name: story-consensus-node
        state: restarted

    - name: Check story-consensus-node service status
      systemd:
        name: story-consensus-node
      register: consensus_service_status

    - name: Check story-geth-node service status
      systemd:
        name: story-geth-node
      register: geth_service_status

    - name: Display service statuses
      debug:
        msg: 
          - "Story Consensus Node service status: {{ consensus_service_status.status.ActiveState }}"
          - "Story Geth Node service status: {{ geth_service_status.status.ActiveState }}"