---
- name: Update Story-Geth Client
  hosts: all
  become: true

  vars:
    geth_version: "0.10.0"
    home_dir: "/root"

  tasks:
    - name: Stop story-geth-node service
      systemd:
        name: story-geth-node
        state: stopped  

    - name: Remove existing geth binary
      file:
        path: "/usr/local/bin/geth"
        state: absent

    - name: Download new version of story-geth
      get_url:
        url: "https://github.com/piplabs/story-geth/releases/download/v{{ geth_version }}/geth-linux-amd64"
        dest: "/usr/local/bin/geth"
        mode: '0755'
        force: yes

    - name: Start story-geth-node service
      systemd:
        name: story-geth-node
        state: started

    - name: Check story-geth-node service status
      systemd:
        name: story-geth-node
      register: service_status

    - name: Display service status
      debug:
        var: service_status.status
