---
- name: Update Story Consensus Node
  hosts: all
  become: true

  vars:
    story_version: "0.12.1"
    home_dir: "/root"

  tasks:
    - name: Stop story-consensus-node service
      systemd:
        name: story-consensus-node
        state: stopped

    - name: Stop story-geth-node service
      systemd:
        name: story-geth-node
        state: stopped

    - name: Remove existing story binary
      file:
        path: "/usr/local/bin/story"
        state: absent

    - name: Download and install story binary
      get_url:
        url: "https://github.com/piplabs/story/releases/download/v{{ story_version }}/story-linux-amd64"
        dest: "/usr/local/bin/story"
        mode: '0755'
        force: yes

    - name: Start story-geth-node service
      systemd:
        name: story-geth-node
        state: started

    - name: Start story-consensus-node service
      systemd:
        name: story-consensus-node
        state: started

    - name: Check story-consensus-node service status
      systemd:
        name: story-consensus-node
      register: consensus_service_status

    - name: Check story-geth-node service status
      systemd:
        name: story-geth-node
      register: geth_service_status

    - name: Display service statuses
      debug:
        msg: 
          - "Story Consensus Node service status: {{ consensus_service_status.status.ActiveState }}"
          - "Story Geth Node service status: {{ geth_service_status.status.ActiveState }}"