{
 "title": "Node Monitoring Story",
 "description": "Dashboard for cometbft, go prometheus metrics exported via the cosmos-sdk.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes, namespace)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up",
   "type": "stat",
   "description": "Running status of instance",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of open file descriptors",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "open_fds"
    },
    {
     "expr": "process_max_fds{instance=\"$instance\"}",
     "legendFormat": "Process Max fds"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Total open file descriptors",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{namespace=~\"^($namespace)$\",instance=\"$instance\"}",
     "legendFormat": "num open fds"
    }
   ]
  },
  {
   "title": "Virtual memory size",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "virtual_memory"
    },
    {
     "expr": "process_virtual_memory_max_bytes{instance=\"$instance\"}",
     "legendFormat": "virtual_memory_max"
    }
   ]
  },
  {
   "title": "Number of bytes allocated",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"$instance\"}",
     "legendFormat": "alloc_bytes"
    },
    {
     "expr": "go_memstats_alloc_bytes_total{instance=\"$instance\"}",
     "legendFormat": "alloc_bytes_total"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "Resident and Virtual memory size in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=~\"^($namespace)$\", instance=\"$instance\"}",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{namespace=~\"^($namespace)$\", instance=\"$instance\"}",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "Heap Stats",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_heap_alloc(bytes)"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_heap_inuse"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_heap_idle"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "go_memstats_heap_sys_bytes"
    }
   ]
  },
  {
   "title": "Total Goroutines",
   "type": "timeseries",
   "description": "Number of goroutines that currently exist",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"^($namespace)$\",instance=\"$instance\"}",
     "legendFormat": "num goroutines"
    }
   ]
  },
  {
   "title": "Other Run Time Allocations Memory Usage",
   "type": "timeseries",
   "description": "Number of bytes used for other system allocations",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_other_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "memstats_other_sys"
    }
   ]
  },
  { "title": "Cometbft", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Block Height",
   "type": "stat",
   "description": "/status sync_info number",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missed Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{instance=\"$instance\"} - cometbft_consensus_latest_block_height{instance=\"$instance\"} - 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Validators",
   "type": "stat",
   "description": "Number of validators",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Peers",
   "type": "timeseries",
   "description": "Number of peers node is connected to",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{instance=\"$instance\"}",
     "legendFormat": "num peers"
    }
   ]
  },
  {
   "title": "Number of Transactions",
   "type": "timeseries",
   "description": "Number of transactions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{instance=\"$instance\"}",
     "legendFormat": "num txs"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "timeseries",
   "description": "Total transactions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{instance=\"$instance\"}",
     "legendFormat": "consensus total txs"
    }
   ]
  },
  {
   "title": "Uncommitted Txs",
   "type": "timeseries",
   "description": "Number of uncommitted transactions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "cometbft_mempool_size{instance=\"$instance\"}",
     "legendFormat": "num of uncommitted txs"
    },
    {
     "expr": "rate(cometbft_mempool_failed_txs{instance=\"$instance\"} [5m])",
     "legendFormat": "failed tx rate"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "description": "Block size in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{instance=\"$instance\"}",
     "legendFormat": "Block Size(bytes)"
    }
   ]
  },
  {
   "title": "Peer Network Input",
   "type": "timeseries",
   "description": "Number of bytes per channel received from a given peer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (peer_id) (rate(cometbft_p2p_peer_receive_bytes_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "peer {{peer_id}}"
    }
   ]
  },
  {
   "title": "Peer Network Output",
   "type": "timeseries",
   "description": "Number of bytes per channel sent to a given peer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (peer_id) (rate(cometbft_p2p_peer_send_bytes_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "peer {{peer_id}}"
    }
   ]
  },
  {
   "title": "Peer Network Output - Pending",
   "type": "timeseries",
   "description": "Number of pending bytes to be sent to a given peer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (peer_id) (rate(cometbft_p2p_peer_pending_send_bytes{instance=\"$instance\"}[5m]))",
     "legendFormat": "peer {{peer_id}}"
    }
   ]
  },
  {
   "title": "Mempool Tx Size",
   "type": "timeseries",
   "description": "Transaction sizes in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "cometbft_mempool_size{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Consensus Block Parts",
   "type": "timeseries",
   "description": "Sum of blockparts transmitted by peer in 5m timeframe",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (peer_id) (rate(cometbft_consensus_block_parts{instance=\"$instance\"}[5m]))",
     "legendFormat": "peer {{peer_id}}"
    }
   ]
  },
  {
   "title": "Mempool Recheck Times",
   "type": "timeseries",
   "description": "Number of transactions rechecked in the mempool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "cometbft_mempool_size{instance=\"$instance\"}",
     "legendFormat": "Mempool Recheck Times"
    }
   ]
  },
  {
   "title": "Consensus Height",
   "type": "timeseries",
   "description": "Number of transactions rechecked in the mempool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "cometbft_consensus_height{instance=\"$instance\"}",
     "legendFormat": "Cometbft Consensus Height"
    }
   ]
  }
 ]
}